name: horsesandheroes
favicon: null
layout_spectrum: 0.89934
typography_spectrum: 0.99643
title: 'Equine Therapy Solutions '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4f4'
    - '#3b384b'
    - '#409a9a'
    - '#416679'
    - '#955952'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
